### ISSUE TITLE
cicyle dependecies

### ISSUE THREAD

**Issue by yuu2lee4** [koajs/generic-session#106]
when i use koa-generic-session-mongo with generic-session in koa2, it tell me cicyle dependecies

**Comment by dead-horse** [comment]
can you give some detail error messages?

**Comment by yuu2lee4** [comment]
no matter i use koa-convert or not
![image](https://cloud.githubusercontent.com/assets/8046366/20709289/630a5624-b66f-11e6-9e55-d23b2048bbe2.png)

**Comment by dead-horse** [comment]
i think it's a runtime error thrown by bson, your session data contains circular reference?

**Comment by yuu2lee4** [comment]
no, i just get a user from mongodb , and set it to session.user
