### ISSUE TITLE
regenerateSession是不是有问题

### ISSUE THREAD

**Issue by fred1218** [koajs/generic-session#109]
this.regenerateSession，你文档中说

> Calling this.regenerateSession will destroy any existing session and generate a new, empty one in its place. The new session will have a different ID.

但是，我在保存session时，调用这个方法，为什么sessionid还是同一个，你源码里加那个判断干嘛，，，我需要sessionId不同，以配合安全测试

**Comment by donggw2030521** [comment]
![image](https://cloud.githubusercontent.com/assets/5877812/21474927/c5f94b7c-cb60-11e6-91b3-b17e1d265b46.png)

**Comment by donggw2030521** [comment]
打开登录页时：
![image](https://cloud.githubusercontent.com/assets/5877812/21474952/e8c89ff4-cb60-11e6-8696-a52a2b1f6678.png)

**Comment by donggw2030521** [comment]
do login:
![image](https://cloud.githubusercontent.com/assets/5877812/21474966/065c407a-cb61-11e6-8fed-0f91b3f058c3.png)
输出见第一张图，为嘛sessionId没变化。。

**Comment by donggw2030521** [comment]
。。我的错，，yield

**Comment by donggw2030521** [comment]
`await co(ctx.regenerateSession())` 这样就Ok了，。。不过大神干嘛不重构下代码完美支持KOA2，感觉在koa2中这样用不伦不类啊。。。。

**Comment by kingjerod** [comment]
I am seeing this problem too. Calls to `await ctx.regenerateSession()` seem to do nothing. Turning on debug, I never see the `debug('regenerating session');` message. It's possible this does not work with Koa v2. I'm using the conversion posted here: https://github.com/koajs/generic-session/issues/59

**Comment by kingjerod** [comment]
@donggw2030521 I switched over to using https://github.com/longztian/koa-session-minimal 

It's a drop in replacement for this library and supports Koa v2 async/await. The only difference I've found is you call `await ctx.sessionHandler.regenerateId();` to get a new session id.
