### ISSUE TITLE
refresh session error: Cannot read property 'done' of undefined

### ISSUE THREAD

**Issue by AngryBaby** [koajs/generic-session#116]
koa version is < 2.0

the project setting is

app.use(session({
	store: new MongoStore(config.mongodb)
}))

when start run, it occurs this error
koa-generic-session:session new session and do not modified +149ms
  koa-generic-session:session refresh session error: Cannot read property 'done' of undefined +1ms
  xxx GET /index 500 887ms -

  TypeError: Cannot read property 'done' of undefined

how to fix it?

**Comment by dead-horse** [comment]
looks like it is an error thrown by MongoStore when save or destroy the session
