### ISSUE TITLE
SessionId generation

### ISSUE THREAD

**Issue by deltasquare4** [koajs/generic-session#35]
Hello,

I am trying to write a bit of server-side tracking to my koa application. Turns out, koa-generic-session middleware doesn't generate sessionId and store it inside koa app context before yielding to next middleware. As a result, I don't have a way to uniquely identify a user until second request is made.

I don't understand whether this is intentional or I'm missing something very obvious.

**Comment by dead-horse** [comment]
please try `koa-generic-session@1.4.0` to see if it fixed this problem?

**Comment by deltasquare4** [comment]
Perfect! Thank you very much. :+1:
