### ISSUE TITLE
Bug: user gets kicked off

### ISSUE THREAD

**Issue by iliakan** [koajs/generic-session#45]
Let's take a site with 15 mins session cookie timeout as an example.

Here's what happens:

1) Bob gets a session. 
2) Bot interacts with the site without modifying the session. He does not get any cookie renewal because of that.
3) After 15 minutes, Bob's cookie expires and he is kicked off.

Using `rolling: true` seems to prevent this (but resubmits whole session to db each time, not optimized).

But... the behavior is kind of strange, it seems natural that we don't want to kick out Bob while he's browsing the site. Maybe make session time-out on inactivity period by default?

**Comment by dead-horse** [comment]
maybe we should set a logger exprie time like 1 day. and if Bob clicked ***Remember me***, give him a much logger  expire time in cookie's setting.

**Comment by halt-hammerzeit** [comment]
@iliakan Ilya, have a look at my fix for this issue:
https://github.com/koajs/generic-session/issues/76

**Comment by iliakan** [comment]
@halt-hammerzeit it's not an issue for me any more, because `rolling:true` and resaving session each time. 

Maybe that was a question about making the behavior default or pushing it in the docs, cause it's kind of "what we used to want".
