### ISSUE TITLE
Add koa-pg-session in the list of stores

### ISSUE THREAD

**Issue by TMiguelT** [koajs/generic-session#46]
Hi! I just made a store implementation using Postgres, [located here](https://github.com/TMiguelT/koa-pg-session). If it seems alright to you, could it be added to the list of store implementations in the readme? Thanks so much.

**Comment by dead-horse** [comment]
please send a PR : )

**Comment by TMiguelT** [comment]
Okay it just seemed a waste to make a fork just to add one line to the readme.

But here's a PR! https://github.com/koajs/generic-session/pull/47
