### ISSUE TITLE
Session hijacking?

### ISSUE THREAD

**Issue by TMiguelT** [koajs/generic-session#49]
Just out of interest, is there anything in this module that could prevent session hijacking? So if someone randomly generates session ID cookies, could they eventually find a real session and use it?

**Comment by bitinn** [comment]
Default options is to have `signed: true` enabled, which means cookies are obfuscated with a unique key and check against its signature, which make this attack more or less impossible.

**Comment by TMiguelT** [comment]
Ah thank you! For anyone in the future/my own reference I looked up the [express docs](https://github.com/pillarjs/cookies#cookiesset-name--value---options--) on which this is based, and it says:
>Another cookie of the same name with the .sig suffix appended will also be sent, with a 27-byte url-safe base64 SHA1 value representing the hash of cookie-name=cookie-value against the first Keygrip key. This signature key is used to detect tampering the next time a cookie is received.
