### ISSUE TITLE
Koa 2

### ISSUE THREAD

**Issue by crisward** [koajs/generic-session#59]
Any plans to update for koa2 ?

**Comment by crisward** [comment]
For anyone else playing with koa2, this can be used with koa-convert.
eg, for sequelize sessions.... 

```
var Koa            = require('koa')
var app            = new Koa();
var session      = require('koa-generic-session')
app.use(convert(session({store: sequelizeStore.create(sequelize)})))
```

**Comment by dead-horse** [comment]
Of cause, I'm a little busy these days, so PR's welcome! 

I'm not sure if we should rewrite this module with async function (babel), but I'm -1 to rewrite this with pure `Promise`.

**Comment by mekwall** [comment]
I've begun my PR here: https://github.com/koajs/generic-session/pull/81. Not only with Koa 2.0 support but refactored to use async functions.

**Comment by andyhu** [comment]
Is there any progress? I actually tested async / await in node 7.0 and it's not faster than bluebird. So what's the considerations for not using pure Promise?

**Comment by dodekeract** [comment]
@andyhu both `Promise` and `async` aren't used because they're fast, they're used because they make writing async code easier. IMHO `async` leads to easier to understand code.

**Comment by jpravetz** [comment]
Does using `async` require the use of node7? Not sure if koa2 already has that requirement, or if it's written in pure Promises.

**Comment by dodekeract** [comment]
@jpravetz `async` doesn't necessarily require Node 7. You can (and IMHO should) use Babel which will transpile it even for older node versions.

**Comment by jpravetz** [comment]
Requiring someone to use Babel when they're not already doing so doesn't seem like a good choice to me. Back to my point, which is not to needlessly introduce dependencies that are not already there. If koa2 requires node7 or Babel then great.

**Comment by sqrthree** [comment]
Any progress? Koa2 has been released.

**Comment by Baira** [comment]
Hope this is in progress :)

**Comment by nsimmons** [comment]
I put up #123 to address this. Just waiting on review.

**Comment by igoradamenko** [comment]
It looks like this issue may be closed because the PR was merged two years ago :-)

**Comment by niftylettuce** [comment]
thx
