### ISSUE TITLE
Why save `cookie` settings inside session object?

### ISSUE THREAD

**Issue by halt-hammerzeit** [koajs/generic-session#72]
I'm using `this.session` to store data.
And there is some `cookie` object with the cookie settings.
Why is it placed there?
My opinion is that it's not needed there and should be removed from there.
I don't care what are the cookie options, I don't need them.
They take space.
With millions of sessions that can exhaust ram or disk space.

**Comment by halt-hammerzeit** [comment]
Ok, so since there's no reason to store cookie options in session data then I just removed it.
https://github.com/halt-hammerzeit/generic-session/commit/4c1075a7df422353e0db446c2f1ad9d855707416
It works now.

**Comment by dead-horse** [comment]
the reason we store the cookie object in session data is that we can change the cookie options(`maxage` or something else) for any specific user.

**Comment by halt-hammerzeit** [comment]
I still don't think that's useful but okay

**Comment by longztian** [comment]
I got hit by the same question. searched to found this thread
In my option, we shouldn't store cookie data in the session object, they are stored in a browser.
