### ISSUE TITLE
Remove koa:sid.sig cookie

### ISSUE THREAD

**Issue by halt-hammerzeit** [koajs/generic-session#73]
Here:
https://github.com/koajs/generic-session/blob/master/lib/session.js#L97

```
    reset: function() {
      this.cookies.set(key, null);
      this.cookies.set(key + '.sig', null);
    }
```

**Comment by dead-horse** [comment]
LGTM.  PR?

**Comment by halt-hammerzeit** [comment]
@dead-horse Yeah, here you go.
https://github.com/koajs/generic-session/pull/74/files
This should work.
