### ISSUE TITLE
prolong session TTL on each request

### ISSUE THREAD

**Issue by catamphetamine** [koajs/generic-session#76]
Currently if a user browses a website but doesn't change his session data then the session times out.
I'm proposing this change to your library which fixes the issue:
https://github.com/halt-hammerzeit/generic-session/commit/c7c13fc7b1a5d7b22dc2db192fe7d11c1d4b08f9
https://github.com/halt-hammerzeit/generic-session/commit/150d41e3df62545486cb61079f8ab321cdcb6fbf

It also prolongs session id http Cookie

**Comment by halt-hammerzeit** [comment]
The corresponding commit to `koa-redis`
@DaAwesomeP
https://github.com/halt-hammerzeit/koa-redis/commit/0f540691ffa244ab1f299c1e9322155f9dc4d2a8

**Comment by dead-horse** [comment]
If you want to prelong session, why not turn `options.rolling` to true ?

**Comment by halt-hammerzeit** [comment]
But what does it do?
The documentation only says that `rolling session, always reset the cookie and sessions, defaults to false`.
I don't want my session to be reset on every request because the point of the session is to retain data in-between requests.

**Comment by evan-king** [comment]
It does what you want (reset the timeout of session and cookie, not their actual contents) provided it won't be an issue that *every* request keeps the session alive (potentially including requests triggered by automated polling, which I'll bring up in another issue).
