### ISSUE TITLE
When I Set session = null, signed Cookied hasn't been remove

### ISSUE THREAD

**Issue by CoderIvan** [koajs/generic-session#79]
From [Example](https://github.com/koajs/generic-session/blob/master/example/app.js):

When I visit [http://localhost:3000/get](), I get two cookies:

![image](https://cloud.githubusercontent.com/assets/7960859/13213016/c921079a-d980-11e5-90c4-1ad3f16fbc0b.png)

But When I visit [http://localhost:3000/remove](), there `koa.sid.sig` hasn't been remove

![image](https://cloud.githubusercontent.com/assets/7960859/13213083/4e7723de-d981-11e5-92f0-99e38cfea84e.png)

**Comment by CoderIvan** [comment]
https://github.com/koajs/generic-session/blob/master/lib/session.js#L97

I think the code `this.cookies.set(key, null)` should be change to `this.cookies.set(key, null, {signed: cookie.signed})`

**Comment by dead-horse** [comment]
there is a PR working on this: https://github.com/koajs/generic-session/pull/74/files

**Comment by CoderIvan** [comment]
Thanks
