### ISSUE TITLE
How to manually save session from `ctx.session`?

### ISSUE THREAD

**Issue by niftylettuce** [koajs/generic-session#80]
e.g. I want to save session in my error handler middleware, how do I do that?

**Comment by tbenst** [comment]
I'm having a similar issue--unable to save the session when using a socket.io listener

Can read and write:
```
router.get('/count', ctx => {
    var session = ctx.session;
    session.count = session.count || 0;
    session.count++;
    ctx.body = session.count;
})
```

Can only read:
```
io.on('test', (ctx, data) => {
    console.log('test get count', ctx.session.count)
    var session = ctx.session;
    session.count = session.count || 0;
    session.count++;
})
```

**Comment by tbenst** [comment]
Just as a warning for others, it appears that koa-generic-session does not allow modification to session from a fetch call.

browser:
```
fetch('/count', {
    method: 'POST',
    headers: {
        count: 1,
    }
})
fetch('/count', {
    method: 'POST',
    headers: {
        count: 2,
    }
})
```

server:
```
router.post('/count', (ctx) => {
    var session = ctx.session
    console.log('sesh1', ctx.session)
    session.count = session.count || 0
    session.count = session.count + ctx.request.header.count
    console.log('sesh2', ctx.session)
    ctx.status = 200   
});
```

**Comment by hedgerh** [comment]
im having the same read only issue in websockets while using `koa-session` and `koa-websocket`.  tried switching to `generic-session` using a redis store and had the same issue.

@tbenst did you ever find a solution to this?

**Comment by tbenst** [comment]
@hedgerh haven't tried it yet but this appears to outline a solution: http://stackoverflow.com/questions/26643370/get-user-id-socket-io-passport-koa.

If you do try it, please do post if it works and/or the code, cheers!

**Comment by niftylettuce** [comment]
I am just not going to use this package anymore, I'm going to write my own or find something else.  This thing needs a major refactor, it's a 🍝 monster.

**Comment by niftylettuce** [comment]
Closed per https://github.com/koajs/generic-session/issues/94#issuecomment-233479006
