### ISSUE TITLE
How to use with passport?

### ISSUE THREAD

**Issue by crunchtime-ali** [koajs/generic-session#85]
I'm using passport for authentication and want to use generic-session with it to store session data inside Redis.
I just don't have a clue of how to make generic-session work with passport.
Can you point me in the right direction?

I found this repo which does this but it doesn't really seem to use the sessions and I am not sure whether it is correct: https://github.com/dozoisch/koa-react-full-example

**Comment by Globik** [comment]
Is actual?

**Comment by niftylettuce** [comment]
@dj-hedgehog did you figure this out?  @Globik it's relatively simple - let me know if you still need shown how.

**Comment by stephanebachelier** [comment]
There is a complete response on stackoverflow for this exact same demand (made by @dj-hedgehog 😄 )

http://stackoverflow.com/a/36972377
