### ISSUE TITLE
refactor

### ISSUE THREAD

**Issue by dead-horse** [koajs/generic-session#90]
the codebase is like a shit now.

**Comment by Globik** [comment]
Do the codebase modern. With harmony features. 
And your session-generic-mongo dependent on mongodb.js. I wouldn't like to have all this mongodb.js instances in modules. Yes, three mongodb.js: first for mongodb, two for session, third for agenda.js. 
That's no good for diskspace. I need all stuff by hand to make. To drop mongodb, leave only one.
And babel for what? Else one dependending. I removed babel and by hand wrote the code as i like for my need.

**Comment by niftylettuce** [comment]
Please refactor!

**Comment by longztian** [comment]
please get a koa 2.0 version too :)

**Comment by longztian** [comment]
I just did a re-write for Koa 2, released as [koa-session-minimal](https://github.com/longztian/koa-session-minimal).
I have [removed cookie info from session object and session stores](https://github.com/koajs/generic-session/issues/98), as one of my Koa 2 project needs minimum storage usage.
