### ISSUE TITLE
The header contains invalid characters

### ISSUE THREAD

**Issue by nallown** [koajs/generic-session#96]
**Edit:** Found the problem! https://github.com/koajs/generic-session/issues/96#issuecomment-234743407

When running:
```javascript
this.session.count = 12
```

This exception gets thrown:
```
  koa-generic-session set error: The header content contains invalid characters
      at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:351:13)
      at Cookies.set (..project\node_modules\cookies\lib\cookies.js:100:13)
      at Object.options.sessionIdStore.set (..project\node_modules\koa-generic-session\lib\session.js:93:20)
      at Object.saveNow (..project\node_modules\koa-generic-session\lib\session.js:283:26)
      at next (native)
      at onFulfilled (..project\node_modules\co\index.js:65:19)
      at process._tickCallback (node.js:369:9)
```

These are the modules that I used:
```
koa v1.2.0
koa-generic-session v1.11.1
koa-router v5.4.0
```

Can be reproduced with the following application:
```javascript
'use strict'

const koa = require('koa')

const router  = require('koa-router')()
const session = require('koa-generic-session')

const app = koa()

app.keys = ['key']
app.use(session())

router.get('/', function* () {
    this.session.count = 12
    this.body = 'test'
});

app.use(router.routes())

app.listen(3000)
console.log('listening on port 3000')

**Comment by nallown** [comment]
Looks like that it was a issue to do with the newer versions of node. It works fine in version 4.2.6 of node.

It might be worth to consult this change https://github.com/nodejs/node/commit/cf2b714b02 to add support for newer versions of node.

**Comment by dead-horse** [comment]
what version of node are you using?

**Comment by nallown** [comment]
@dead-horse version 4.4.7, anything beyond 4.2.6 doesn't work.

**Comment by dead-horse** [comment]
I can't reproduce this problem.

The default session id is generated by [uid-safe](https://github.com/crypto-utils/uid-safe) which I think won't contains invalid http herder characters ?

**Comment by nallown** [comment]
strange, I'll test it in a clean node environment and see whether that works. I'll update you when I'm done.

**Comment by nallown** [comment]
Works fine in a new environment. I think it might be one of the installed modules interfering with it. Kind of strange how they're interfering even though they're not being loaded or touched at all though. They're just installed. I'll go through the node modules that I've got installed and will figure out which one it

**Comment by nallown** [comment]
Updating koa to version 1.2.1 and koa-generic-session to version 1.11.3 fixed it.
